### ISSUE TITLE
less的判斷

### ISSUE THREAD

**Issue by visionxyz** [ianre657/ComputerOrganization_2017Spring#1]
您好，我看了bottom那邊的代碼，less是根據carry out來的。感覺有點問題，比如我的兩個數都是1000，那麼做減法就是要算1000+1000，因為1000的2-complement也是1000。此時的carryout也會是1。於是less就是1了。但是如果看sum的話是0，所以less是0。我感覺less_out應該看sum，而不是out。雖然您的結果是對的。

**Comment by visionxyz** [comment]
好像知道問題在哪裡了。

**Comment by ianchen-tw** [comment]
我沒有翻程式碼，不夠你ok就行了👌

**Comment by visionxyz** [comment]
感覺距離你上次push也太久了，應該你也忘記了。我現在用sum當less_out也能出來對的結果。他的bonus test case太少了。也看不出到底哪個寫法可能有錯。

**Comment by ianchen-tw** [comment]
@blessxu  你是在說Lab1吧! 這差不多兩年前的作業了 因為沒有寫文件所以我也忘記`bonus_control` 是什麼東西了QQ
Anyway 如果你有什麼疑問還是可以提出來，我會盡量幫你解答!

**Comment by visionxyz** [comment]
我來講一下吧，就是會有一個LST的set，需要解答 a是不是less than b。方法就是a-b，也就是a+b的2's complement，然後判斷正負。我看了看您這裡的code，最後less的值似乎用了cout來判斷，感覺bottom那邊的cout不能當做判斷的理由，sum才是正負的判斷bit。
https://github.com/ianre657/ComputerOrganization_2017Spring/blob/f6b445db44fa70f2ecdca4be1d492bf42d129bde/lab1/sourceCode/alu_bottom.v#L37
就是這裡。真的非常感謝了。

**Comment by visionxyz** [comment]
您這樣的寫法之所以答案是對的，是因為在compare裡面做了調整。
比如1000000000000000和1000000000000000比較SLT，如果根據cout來判斷的話，cout=1，less就是1。也就是less成立了，不過compare裡面居然還要求less的情況下不能equal（LT: out <=  less & ~equal;），這其實是非常奇怪的要求，less成立怎麼還會equal呢。答案其實是會的，這段程式會在equal的情況下還判斷為less。不過有了這段矯正的code，所以最後的答案是對的。
